# Generated by Django 5.0.1 on 2024-01-11 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_dead",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="target_name",
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_dead", models.BooleanField(default=False)),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("target_pk", models.IntegerField(default=None)),
                ("kills", models.IntegerField(default=0)),
                ("is_playing", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmations", models.IntegerField(default=0)),
                ("target_confirmed", models.BooleanField(default=False)),
                ("killer_confirmed", models.BooleanField(default=False)),
                (
                    "killer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killer_checker",
                        to="users.player",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_checker",
                        to="users.player",
                    ),
                ),
            ],
        ),
    ]
