# Generated by Django 5.0.1 on 2024-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_dead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='target_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
