# Generated by Django 5.0.1 on 2024-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_player_target_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='shown_to_killer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checker',
            name='shown_to_target',
            field=models.BooleanField(default=False),
        ),
    ]
