# Generated by Django 5.0.1 on 2024-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_checker_shown_to_killer_checker_shown_to_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
    ]
