# Generated by Django 5.0.1 on 2024-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_player_is_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="in_waiting",
            field=models.BooleanField(default=False),
        ),
    ]
