# Generated by Django 5.0.1 on 2024-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_player_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='shown_to_killer',
        ),
        migrations.RemoveField(
            model_name='checker',
            name='shown_to_target',
        ),
        migrations.AddField(
            model_name='checker',
            name='action_performed',
            field=models.BooleanField(default=False),
        ),
    ]
