# Generated by Django 5.0.1 on 2024-01-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_checker_shown_to_killer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="have_eliminated_today",
            field=models.BooleanField(default=False),
        ),
    ]
