# Generated by Django 5.0.1 on 2024-01-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_checker_self_defense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checker",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_checker",
                to="users.player",
            ),
        ),
    ]
