# Generated by Django 5.0.1 on 2024-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_checker_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_out', models.BooleanField(default=False)),
                ('target_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_group_pk', models.IntegerField(blank=True, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('is_playing', models.BooleanField(default=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='users.player')),
            ],
        ),
    ]
