# Generated by Django 5.0.1 on 2024-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_game_alter_agentgroup_is_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="placing_groups",
            field=models.BooleanField(default=False),
        ),
    ]
