# Generated by Django 5.0.1 on 2024-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_game_placing_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentgroup",
            name="is_out",
            field=models.BooleanField(default=False),
        ),
    ]
