# Generated by Django 5.0.1 on 2024-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_agentgroup_is_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(default="Current Game", max_length=35),
        ),
    ]
